### ISSUE TITLE
Issue with hyphen in prefix

### ISSUE THREAD

**Issue by mklopp** [neo4j-labs/neosemantics#210] opened 2021-02-25 15:31 UTC
I am trying out this plugin and came across an issue with using hyphen in prefixes.
So I have a simple ontology with two classes, two individuals and an object property connecting these two individuals.

When using `call n10s.nsprefixes.add("myprefix", "http://www.example.com/example#");` or not setting up a custom prefix so it uses ns0 it all works well.
After fetching the ontology, a call to `/rdf/neo4j/describe/http%3A%2F%2Fwww.example.com%2Fexample%23Enitity1Individual?format=RDF/XML` gives me following output as expected:
```<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF
	xmlns:owl="http://www.w3.org/2002/07/owl#"
	xmlns:myprefix="http://www.example.com/example#"
	xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">

<rdf:Description rdf:about="http://www.example.com/example#Enitity1Individual">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#NamedIndividual"/>
	<rdf:type rdf:resource="http://www.example.com/example#Enitity1"/>
	<myprefix:requires rdf:resource="http://www.example.com/example#Entity2Individual"/>
</rdf:Description>

</rdf:RDF>
```

When using `call n10s.nsprefixes.add("my-prefix", "http://www.example.com/example#");` instead and then fetching the ontology, the same call gives me:
```<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF
	xmlns:owl="http://www.w3.org/2002/07/owl#"
	xmlns:my-prefix="http://www.example.com/example#"
	xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">

<rdf:Description rdf:about="http://www.example.com/example#Enitity1Individual">
	<rdf:type rdf:resource="neo4j://graph.schema#my-prefix__Enitity1"/>
	<my-prefix__requires xmlns="neo4j://graph.schema#" rdf:resource="http://www.example.com/example#Entity2Individual"/>
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#NamedIndividual"/>
</rdf:Description>

</rdf:RDF>
```

As you can see it messed up the usage of the prefix.

**Comment by jbarrasa** [comment] 2021-03-02 14:07
Wow, that's an interesting one, @mklopp 
First of all, thanks for you interest in n10s! ...now let's try to reproduce the issue.

I've tried what you describe and I get the expected behavior, which is that once you load data, n10s will not let you mess with namespaces precisely because of this. Here's what I see:

If you try to redefine a namespace you get an exception like this:
![image](https://user-images.githubusercontent.com/9989143/109659760-f0faa600-7b5f-11eb-8b1e-ae6ad83a5565.png)

Similarly, if you try to delete it to define another one, n10s complains: 
![image](https://user-images.githubusercontent.com/9989143/109659838-0b348400-7b60-11eb-8e9d-76c9331f98b1.png)

So I'm really curious how you've managed to find yourself in the situation you describe above. Is it possible that you've used a backdoor like manipulating the `_NsPrefDef` directly via cypher? It would be great if you could share a step by step script to reproduce that.

Thanks!

JB.

**Comment by mklopp** [comment] 2021-03-02 15:06
Oh excuse me. I forgot to mention, that I reset the database in between. So both variants, would be
1. Having a clean database
2. Doing the resource uri constraint command
3. calling `n10s.graphconfig.init()`
4. calling `n10s.nsprefixes.add("myprefix", "http://www.example.com/example#");` or `n10s.nsprefixes.add("my-prefix", "http://www.example.com/example#");` respectively
5. Calling n10s.rdf.import.fetch with this file 
```<?xml version="1.0"?>
<rdf:RDF xmlns="http://www.example.com/example#"
     xml:base="http://www.example.com/example"
     xmlns:owl="http://www.w3.org/2002/07/owl#"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:xml="http://www.w3.org/XML/1998/namespace"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
     xmlns:example="http://www.example.com/example#">
    <owl:Ontology rdf:about="http://www.example.com/example"/>
    
    <owl:ObjectProperty rdf:about="http://www.example.com/example#requires"/>

    <owl:Class rdf:about="http://www.example.com/example#Enitity1"/>

    <owl:Class rdf:about="http://www.example.com/example#Entity2"/>

    <owl:NamedIndividual rdf:about="http://www.example.com/example#Enitity1Individual">
        <rdf:type rdf:resource="http://www.example.com/example#Enitity1"/>
        <requires rdf:resource="http://www.example.com/example#Entity2Individual"/>
    </owl:NamedIndividual>

    <owl:NamedIndividual rdf:about="http://www.example.com/example#Entity2Individual">
        <rdf:type rdf:resource="http://www.example.com/example#Entity2"/>
    </owl:NamedIndividual>
</rdf:RDF>
```
6. Doing a get request to `/rdf/neo4j/describe/http%3A%2F%2Fwww.example.com%2Fexample%23Enitity1Individual?format=RDF/XML`
7. The result from the request being the two snippets from my initial post. Where the one for `myprefix` is the correct, expected result and the one for `my-prefix` is malformed.

There seems to be an issue with the export of an rdf file when using a hyphen in a prefix.

**Comment by jbarrasa** [comment] 2021-03-13 17:02
Got it. Thanks a lot @mklopp, great catch.

We are planning a release in the next few days and will try to include a fix for this.

Thanks!

JB.

**Comment by mklopp** [comment] 2021-03-15 10:54
Ahh I have seen that regex and thought that it might be because of that.

Thanks for the fix!

**Comment by jbarrasa** [comment] 2021-03-17 13:42
should be included in next release. feel free to reopen if you detect any unexpected behavior

**Closed by jbarrasa** 2021-03-17 13:42 UTC
